# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Panghu1102
email: Ph101102@163.com
description: >-
  Panghu1102的博客！欢迎访问！
twitter_username: Panghu1102
github_username: Panghu1102
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Panghu1102"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "有些好想法总会转瞬即逝，所以如果想到了，就勇敢的尝试一下吧！"
  links:
    - label: "贴吧"
      icon: "fas fa-fw fa-link"
      url: "https://tieba.baidu.com/home/main?id=tb.1.d07df80c.a8EiNjQtA7cwWgVEwH0bmQ?t=1672895272&fr=index"
    - label: "GitHub"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/Panghu1102"
    - label: "小红书"
      icon: "fas fa-fw fa-link"
      url: "https://www.xiaohongshu.com/user/profile/63e64f0f000000002600784a?xsec_token=YB6tdTc5ICPxK5P8K8xUDP23T4nMYVDrRfpsPeKC7M9cI=&xsec_source=app_share&xhsshare=CopyLink&shareRedId=ODlHNjdLNE82NzUyOTgwNjg5OTc7PTpK&apptime=1768901345&share_id=4c7bca359d9a42339cb1e4ce78d53c60"

footer:
  links:
    - label: "贴吧"
      icon: "fas fa-fw fa-link"
      url: "https://tieba.baidu.com/home/main?id=tb.1.d07df80c.a8EiNjQtA7cwWgVEwH0bmQ?t=1672895272&fr=index"
    - label: "GitHub"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/Panghu1102"
    - label: "小红书"
      icon: "fas fa-fw fa-link"
      url: "https://www.xiaohongshu.com/user/profile/63e64f0f000000002600784a?xsec_token=YB6tdTc5ICPxK5P8K8xUDP23T4nMYVDrRfpsPeKC7M9cI=&xsec_source=app_share&xhsshare=CopyLink&shareRedId=ODlHNjdLNE82NzUyOTgwNjg5OTc7PTpK&apptime=1768901345&share_id=4c7bca359d9a42339cb1e4ce78d53c60"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
